# /home/timcherne/code/Trading_Hub/strat_bio_tech/ticker_map.py
ticker_map = {
    # Large/Mid-Cap (for completeness, ~100)
    'AstraZeneca': 'AZN', 'Pfizer': 'PFE', 'Regeneron': 'REGN', 'Gilead Sciences': 'GILD', 'Amgen': 'AMGN',
    'Bristol-Myers Squibb': 'BMY', 'Merck & Co.': 'MRK', 'Novartis': 'NVS', 'Roche': 'RHHBY', 'Sanofi': 'SNY',
    'Eli Lilly': 'LLY', 'AbbVie': 'ABBV', 'Johnson & Johnson': 'JNJ', 'Vertex Pharmaceuticals': 'VRTX',
    'Moderna': 'MRNA', 'BioNTech': 'BNTX', 'Jazz Pharmaceuticals': 'JAZZ', 'Ionis Pharmaceuticals': 'IONS',
    'Biogen': 'BIIB', 'Alnylam Pharmaceuticals': 'ALNY', 'Sarepta Therapeutics': 'SRPT', 'Exelixis': 'EXEL',
    'Incyte': 'INCY', 'United Therapeutics': 'UTHR', 'Neurocrine Biosciences': 'NBIX', 'BioMarin': 'BMRN',
    'Halozyme Therapeutics': 'HALO', 'Ironwood Pharmaceuticals': 'IRWD', 'Natera': 'NTRA', 'Beam Therapeutics': 'BEAM',
    'bluebird bio': 'BLUE', 'CRISPR Therapeutics': 'CRSP', 'Editas Medicine': 'EDIT', 'Intellia Therapeutics': 'NTLA',
    'BridgeBio Pharma': 'BBIO', 'Ultragenyx Pharmaceutical': 'RARE', 'Harmony Biosciences': 'HRMY', 'Travere Therapeutics': 'TVTX',
    'Enanta Pharmaceuticals': 'ENTA', 'Alector': 'ALEC', 'Denali Therapeutics': 'DNLI', 'Cerevel Therapeutics': 'CERE',
    'Karuna Therapeutics': 'KRTX', 'Scholar Rock': 'SRRK', 'Day One Biopharmaceuticals': 'DAWN', 'Nuvalent': 'NUVL',
    'Janux Therapeutics': 'JANX', 'Repare Therapeutics': 'RPTX', 'Maze Therapeutics': 'MAZE', 'Arvinas': 'ARVN',
    'CorMedix': 'CRMD', 'Ventyx Biosciences': 'VTYX', 'TScan Therapeutics': 'TCRX', 'Actinium Pharmaceuticals': 'ATNM',
    'Inhibikase Therapeutics': 'IKT', 'Energy Fuels': 'UUUU', 'DiaMedica Therapeutics': 'DMAC', 'Context Therapeutics': 'CNTX',
    'Lexicon Pharmaceuticals': 'LXRX', 'Capricor Therapeutics': 'CAPR', 'AC Immune': 'ACIU', 'SAVA': 'SAVA',
    'Viridian Therapeutics': 'VRDN', 'Cytokinetics': 'CYTK', 'aTyr Pharma': 'ATYR', 'MoonLake Immunotherapeutics': 'MLTX',
    'OKYO Pharma': 'OKYO', 'IO Biotech': 'IOBT', 'Tiziana Life Sciences': 'TLSA', 'Palvella Therapeutics': 'PLV',
    'Candel Therapeutics': 'CADL', 'Vera Therapeutics': 'VERA', 'Entera Bio': 'ENTX', 'Advaxis': 'ADXS',
    'Alexion Pharmaceuticals': 'ALXN', 'Pharming Group': 'PHAR', 'Zealand Pharma': 'ZLAB', 'Sana Biotechnology': 'SANA',
    'Calliditas Therapeutics': 'CALT', 'Arcus Biosciences': 'RCUS', 'Ziopharm Oncology': 'ZIOP', 'Zymeworks': 'ZYME',
    'Zynerba Pharmaceuticals': 'ZYNE', 'Cardiol Therapeutics': 'CRDL', 'atai Life Sciences': 'ATAI', 'Vigil Neuroscience': 'VIGL',
    'Bright Minds Biosciences': 'DRUG', 'Anebulo Pharmaceuticals': 'ANEB', 'Theriva Biologics': 'TIBT', 'Coya Therapeutics': 'COYA',
    'Annovis Bio': 'ANVS', 'Ampio Pharmaceuticals': 'AMPE', 'AmpliPhi Biosciences': 'APHB', 'AnaptysBio': 'ANAB',
    'Arena Pharmaceuticals': 'ARNA', 'argenx SE': 'ARGX', 'Audentes Therapeutics': 'BOLD', 'Aurinia Pharmaceuticals': 'AUPH',
    'Aduro BioTech': 'ADRO', 'Adaptimmune Therapeutics': 'ADAP', 'ADMA Biologics': 'ADMA', 'Akebia Therapeutics': 'AKBA',
    'Akero Therapeutics': 'AKRO', 'Alkermes': 'ALKS', 'Allakos': 'ALLK', 'Allogene Therapeutics': 'ALLO',
    'Altos Labs': 'ALTS', 'Alzamend Neuro': 'ALZN', 'Amarin': 'AMRN', 'Amicus Therapeutics': 'FOLD',
    'Amylyx Pharmaceuticals': 'AMLX', 'Anavex Life Sciences': 'AVXL', 'Anglepoint': 'ANGL', 'Annexon': 'ANNX',
    'Anika Therapeutics': 'ANIK', 'Annovis Bio': 'ANVS', 'Anthrogenesis': 'ANTH', 'Aprea Therapeutics': 'APRE',
    'Arbutus Biopharma': 'ABUS', 'Aridis Pharmaceuticals': 'ARDS', 'Arrowhead Pharmaceuticals': 'ARWR',
    'Asher Bio': 'ASNB', 'Atara Biotherapeutics': 'ATRA', 'Athersys': 'ATHX', 'Atossa Therapeutics': 'ATOS',
    'Aurigene Discovery Technologies': 'AURI', 'Avacta Group': 'AVCT', 'Avid Bioservices': 'CDMO',
    'Axsome Therapeutics': 'AXSM', 'Aytu BioPharma': 'AYTU', 'Azitra': 'AZTR', 'Bavarian Nordic': 'BAVA',
    'Beam Therapeutics': 'BEAM', 'Bellicum Pharmaceuticals': 'BLCM', 'Bellerophon Therapeutics': 'BLPH',
    'Benitec Biopharma': 'BNTC', 'BioAtla': 'BCAB', 'BioCryst Pharmaceuticals': 'BCRX', 'BioDelivery Sciences': 'BDSI',
    'Biohaven': 'BHVN', 'BioLineRx': 'BLRX', 'BioMarin': 'BMRN', 'BioNTech': 'BNTX',
    'Bio-Rad Laboratories': 'BIO', 'BioRestorative Therapies': 'BRTX', 'Biosig Technologies': 'BSGM',
    'BioSpecifics Technologies': 'BSTC', 'BioVie': 'BIVI', 'Bioventus': 'BVS', 'Black Diamond Therapeutics': 'BDTX',
    'Bluebird Bio': 'BLUE', 'Blyth': 'BTH', 'Bolt Biotherapeutics': 'BOLT', 'Bone Biologics': 'BBLG',
    'Bostwick Laboratories': 'BSTW', 'BrainStorm Cell Therapeutics': 'BCLI', 'BriaCell Therapeutics': 'BCTX',
    'Bright Minds Biosciences': 'DRUG', 'Bristol Myers Squibb': 'BMY', 'BubR1': 'BBR1', 'Caladrius Biosciences': 'CLBS',
    'Calithera Biosciences': 'CALA', 'Can-Fite BioPharma': 'CANF', 'Capricor Therapeutics': 'CAPR',
    'Cardiff Oncology': 'CRDF', 'CareDx': 'CDNA', 'Carmot Therapeutics': 'CRMT', 'Casdin Capital': 'CSGP',
    'Casgevy': 'CRSP', 'Catalyst Biosciences': 'CBIO', 'Catabasis Pharmaceuticals': 'CATB', 'Cava Healthcare': 'CAVA',
    'Cel-Sci': 'CVM', 'Cell Therapeutics': 'CTIC', 'Celltrion': '068270.KS', 'Centessa Pharmaceuticals': 'CNTA',
    'Cerecor': 'CERC', 'Checkpoint Therapeutics': 'CKPT', 'Chimerix': 'CMRX', 'Chinook Therapeutics': 'KDNY',
    'ChromaDex': 'CDXC', 'Chronos Therapeutics': 'CTHR', 'Citius Pharmaceuticals': 'CTXR', 'Clene Nanomedicine': 'CLNN',
    'Clearmind Medicine': 'CMND', 'Codexis': 'CDXS', 'Colucid Pharmaceuticals': 'CLCD', 'Coltiva': 'CTVA',
    'Complement Therapeutics': 'CMPL', 'Conatus Pharmaceuticals': 'CNAT', 'Connective Orthopaedics': 'COVR',
    'Corbus Pharmaceuticals': 'CRBP', 'Curevo Vaccine': 'CVAC', 'Curis': 'CRIS',
    'Cyclacel Pharmaceuticals': 'CYCC', 'Cymabay Therapeutics': 'CBAY', 'Cynata Therapeutics': 'CYP.AX',
    'Cytokinetics': 'CYTK', 'CytomX Therapeutics': 'CTMX', 'Daiichi Sankyo': 'DSKY',
    'Delcath Systems': 'DCTH', 'DelMar Pharmaceuticals': 'DMPI', 'Denali Therapeutics': 'DNLI',
    'DerivaBio': 'DRUG', 'Dextera Surgical': 'DXTR', 'Dianthus Therapeutics': 'DNTH',
    'Dicerna Pharmaceuticals': 'DRNA', 'Discuva': 'DSCV.L', 'Doximity': 'DOCS',
    'DS Biopharma': 'DSBP', 'Dynavax Technologies': 'DVAX', 'Eagle Pharmaceuticals': 'EGRX',
    'Eledon Pharmaceuticals': 'ELDN', 'Elevation Oncology': 'ELEV', 'Elicio Therapeutics': 'ELTX',
    'Eloxx Pharmaceuticals': 'ELOX', 'EMD Serono': 'MRK', 'Enanta Pharmaceuticals': 'ENTA',
    'Enbrel': 'AMGN', 'Enlivex Therapeutics': 'ENLV', 'Enterin': 'ENTR',
    'Enzyvant Therapeutics': 'ENZY', 'EpiDestiny': 'EPST', 'Equillium': 'EQ',
    'Eton Pharmaceuticals': 'ETON', 'Evofem Biosciences': 'EVFM', 'Exicure': 'XCUR',
    'F2G': 'F2G.L', 'Faron Pharmaceuticals': 'FARN.HE', 'Fate Therapeutics': 'FATE',
    'FibroGen': 'FGEN', 'Fortress Biotech': 'FBIO', 'Fortress Value Acquisition': 'FVAC',
    'Forty Seven': 'FTSV', 'Fresenius Medical Care': 'FMS', 'Fulcrum Therapeutics': 'FULC',
    'Galapagos': 'GLPG', 'Galera Therapeutics': 'GRTX', 'Gilead Sciences': 'GILD',
    'Glaukos': 'GKOS', 'Glenmark Pharmaceuticals': 'GLENMARK.NS', 'Global Blood Therapeutics': 'GBT',
    'Gossamer Bio': 'GOSS', 'Grey Wolf Therapeutics': 'GWTX', 'Gritstone Bio': 'GRTS',
    'GSK': 'GSK', 'GT Biopharma': 'GTBP', 'H1': 'HONE', 'Hailia Therapeutics': 'HAIL',
    'Hansa Biopharma': 'FN', 'Harmony Biosciences': 'HRMY', 'Hookipa Pharma': 'HOOK',
    'Humacyte': 'HUMA', 'Huyabio International': 'HYB', 'Iovance Biotherapeutics': 'IOVA',
    'Ipsen': 'IPSEY', 'Ironwood Pharmaceuticals': 'IRWD', 'Janus Henderson Investors': 'JHG',
    'Janssen Pharmaceuticals': 'JNJ', 'Jazz Pharmaceuticals': 'JAZZ', 'Jounce Therapeutics': 'JNCE',
    'Karuna Therapeutics': 'KRTX', 'Keros Therapeutics': 'KROS', 'Kite Pharma': 'GILD',
    'Krystal Biotech': 'KRYS', 'Kura Oncology': 'KURA', 'Kyowa Kirin': 'KYKKF',
    'LAVA Therapeutics': 'LVTX', 'Legend Biotech': 'LEGN', 'LeMaitre Vascular': 'LMAT',
    'Lexicon Pharmaceuticals': 'LXRX', 'Ligand Pharmaceuticals': 'LGND', 'Lilly': 'LLY',
    'Longboard Pharmaceuticals': 'LBPH', 'Lyell Immunopharma': 'LYEL', 'MaaT Pharma': 'MAAT.PA',
    'MacroGenics': 'MGNX', 'Madrigal Pharmaceuticals': 'MDGL', 'Magenta Therapeutics': 'MGTA',
    'MannKind Corporation': 'MNKD', 'Marinus Pharmaceuticals': 'MRNS', 'Maze Therapeutics': 'MAZE',
    'Medicus Pharma': 'MDCX', 'MeiraGTx Holdings': 'MGTX', 'Merck KGaA': 'MKKGY',
    'Merck & Co': 'MRK', 'Merck Sharp & Dohme': 'MRK', 'Mersana Therapeutics': 'MRSN',
    'Metsera': 'MTSA', 'Miltenyi Biotec': 'MBIO', 'Moderna': 'MRNA',
    'Molecular Templates': 'MTEM', 'MoonLake Immunotherapeutics': 'MLTX', 'Morphic Holding': 'MORF',
    'Mustang Bio': 'MBIO', 'Natera': 'NTRA', 'Nektar Therapeutics': 'NKTR',
    'Neoleukin Therapeutics': 'NLTX', 'Neurocrine Biosciences': 'NBIX', 'Neuropace': 'NPCE',
    'NextCure': 'NXTC', 'Nexus Pharmaceuticals': 'NEXU', 'Novavax': 'NVAX',
    'Novartis': 'NVS', 'Novo Nordisk': 'NVO', 'Nuvalent': 'NUVL',
    'Nutcracker Therapeutics': 'NUTX', 'Ocuphire Pharma': 'OPHR', 'Olema Pharmaceuticals': 'OLMA',
    'OliX Pharmaceuticals': 'OLPX', 'Oncopeptides': 'ONCO', 'Oncternal Therapeutics': 'ONCT',
    'OncoSec Medical': 'ONCS', 'Oncocyte Corporation': 'OCX', 'Oncotelic Therapeutics': 'OTLC',
    'Oncozen Therapeutics': 'ONCT', 'Ono Pharmaceutical': 'OPCFY', 'Opthea Limited': 'OPT',
    'Organovo Holdings': 'ONVO', 'Oruka Therapeutics': 'ORUK', 'Oryx Vision': 'ORYX',
    'Otonomy': 'OTIC', 'Outpost Medicine': 'OUTP', 'Ovid Therapeutics': 'OVID',
    'Owkin': 'OWKN', 'Oxford Biomedica': 'OXB.L', 'Pact Pharma': 'PACT',
    'Palleon Pharmaceuticals': 'PALL', 'Pandion Therapeutics': 'PAND', 'Paratek Pharmaceuticals': 'PRTK',
    'Parvus Therapeutics': 'PVUS', 'Patheon': 'PTHN', 'PDS Biotechnology': 'PDSB',
    'Peptinnovate': 'PEPT', 'Perceptive Advisors': 'PERS', 'Pfizer': 'PFE',
    'PharmAla Biotech': 'PHRM', 'Pharming Group': 'PHAR', 'PhaseBio Pharmaceuticals': 'PHAS',
    'Phoenix Biotechnology': 'PHX', 'Pliant Therapeutics': 'PLRX', 'Precigen': 'PGEN',
    'ProKidney': 'PROK', 'Prothena Corporation': 'PRTA', 'Protara Therapeutics': 'TARA',
    'PTC Therapeutics': 'PTCT', 'PureTech Health': 'PRTC', 'Pyxis Oncology': 'PYXS',
    'Rapa Therapeutics': 'RAPA', 'Recursion Pharmaceuticals': 'RXRX', 'Regeneron Pharmaceuticals': 'REGN',
    'Rejuvenate Bio': 'REJU', 'Relay Therapeutics': 'RLAY', 'Replimune Group': 'REPL',
    'Rezolute': 'RZLT', 'Rocket Pharmaceuticals': 'RCKT', 'Rubius Therapeutics': 'RUBY',
    'Sana Biotechnology': 'SANA', 'Sarepta Therapeutics': 'SRPT', 'Satellos Bioscience': 'STBS',
    'Schrödinger': 'SDGR', 'Seagen': 'SGEN', 'Selecta Biosciences': 'SELB',
    'Sera Prognostics': 'SERA', 'Seres Therapeutics': 'MCRB', 'Silicon Therapeutics': 'SILT',
    'Sio Gene Therapies': 'SIOX', 'Skye Biosciences': 'SKYE', 'Sobi': 'SOBI',
    'Sorrento Therapeutics': 'SRNE', 'SpringWorks Therapeutics': 'SWTX', 'Sqz Biotechnologies': 'SQZ',
    'Sstellantis': 'STLA', 'Summit Therapeutics': 'SMMT', 'Surfaxin': 'DSKX',
    'Synlogic': 'SYBX', 'T2 Biosystems': 'TTOO', 'Tactile Medical': 'TCMD',
    'Takeda Pharmaceutical': 'TAK', 'Talis Biomedical': 'TBLT', 'Tango Therapeutics': 'TNGX',
    'Targeted Genetics': 'TGEN', 'Tarsus Pharmaceuticals': 'TARS', 'Taysha Gene Therapies': 'TSHA',
    'TC BioPharm': 'TCBP', 'Tempest Therapeutics': 'TEM', 'Tenaya Therapeutics': 'TNYA',
    'Tenet Healthcare': 'THC', 'Terns Pharmaceuticals': 'TERN', 'Tetraphase Pharmaceuticals': 'TTPH',
    'TG Therapeutics': 'TGTX', 'Theravance Biopharma': 'TPTX', 'Theriva Biologics': 'TIBT',
    'Thirty Respiratory': 'THRY', 'Thrombogenic': 'THRX', 'Tivic Health Systems': 'TIVC',
    'Torii Pharmaceutical': 'TRPHF', 'Torrid Holdings': 'CURV', 'Trillium Therapeutics': 'TRIL',
    'Twist Bioscience': 'TWST', 'UCB': 'UCBJY', 'Ultragenyx Pharmaceutical': 'RARE',
    'Uniqure': 'QURE', 'Upstream Bio': 'UPST', 'Vaccitech': 'VACC',
    'Vanda Pharmaceuticals': 'VNDA', 'Vanguard': 'VGT', 'Vanguard Health Care ETF': 'VHT',
    'Vascular Biogenics': 'VBLT', 'Vaxart': 'VXRT', 'VBI Vaccines': 'VBIV',
    'VenatoRx Pharmaceuticals': 'VNRX', 'Vericel Corporation': 'VCEL', 'Verrica Pharmaceuticals': 'VRCA',
    'Verso Therapeutics': 'VSO', 'Vertex Pharmaceuticals': 'VRTX', 'Verve Therapeutics': 'VERV',
    'Vigil Neuroscience': 'VIGL', 'Viking Therapeutics': 'VKTX', 'Viridian Therapeutics': 'VRDN',
    'Vironova Holding': 'VRNA.ST', 'Virpax Pharmaceuticals': 'VRPX', 'Visterin Pharmaceuticals': 'VSTR',
    'Vita Therapeutics': 'VITA', 'Vividion Therapeutics': 'VVID', 'Vorso Corp': 'VSO',
    'Voxeleron': 'VXR', 'Vycor Medical': 'VYCO', 'Vyntsmusic': 'VNT',
    'X4 Pharmaceuticals': 'XFOR', 'Xencor': 'XNCR', 'Xoma Corporation': 'XOMA',
    'Y-mAbs Therapeutics': 'YMAB', 'Yale University': 'YALE', 'Yatra Online': 'YTRO',
    'Yerba Buena': 'YBNA', 'Yondr Group': 'YONR', 'Yumanity Therapeutics': 'YMTX',
    'Zai Lab': 'ZLAB', 'Zealand Pharma': 'ZLAB', 'Zeva Biosciences': 'ZEVA',
    'Ziopharm Oncology': 'ZIOP', 'Zogenix': 'ZGNX', 'Zometa': 'ZOM',
    'Zosurabalpin': 'ZOSU', 'Zosurabalpin Therapeutics': 'ZOSU', 'Zymeworks': 'ZYME',
    'Zynerba Pharmaceuticals': 'ZYNE', 'Zynex Medical': 'ZYXI', 'Zynga': 'ZNGA',
    'Zymergen': 'ZY', 'Zymovant': 'ZYMV',
    # Micro/Nano-Cap (<$50M)
    'Psyence Biomedical Ltd.': 'PBM', 'Salarius Pharmaceuticals, Inc.': 'SLRX', 'Scinai Immunotherapeutics Ltd.': 'SCNI',
    'CDT Equity Inc.': 'CDT', 'Silexion Therapeutics Corp': 'SLXN', 'Enveric Biosciences, Inc.': 'ENVB',
    'GT Biopharma, Inc.': 'GTBP', 'SciSparc Ltd.': 'SPRC', 'Virax Biolabs Group Limited': 'VRAX',
    'Azitra, Inc.': 'AZTR', 'Moolec Science SA': 'MLEC', 'Aditxt, Inc.': 'ADTX',
    'Revelation Biosciences, Inc.': 'REVB', 'Dermata Therapeutics, Inc.': 'DRMA', 'Indaptus Therapeutics, Inc.': 'INDP',
    'PMGC Holdings Inc.': 'ELAB', 'XORTX Therapeutics Inc.': 'XRTX', 'Biodexa Pharmaceuticals Plc': 'BDRX',
    'Quoin Pharmaceuticals, Ltd.': 'QNRX', 'Aptevo Therapeutics Inc.': 'APVO', 'Onconetix, Inc.': 'ONCO',
    'GRI Bio, Inc.': 'GRI', 'Jaguar Health, Inc.': 'JAGX', 'Spruce Biosciences, Inc.': 'SPRB',
    'Galecto, Inc.': 'GLTO', 'Xenetic Biosciences, Inc.': 'XBIO', 'CNS Pharmaceuticals, Inc.': 'CNSP',
    'Oragenics, Inc.': 'OGEN', 'Purple Biotech Ltd': 'PPBT', 'Clearmind Medicine Inc.': 'CMND',
    'Alaunos Therapeutics, Inc.': 'TCRT', '60 Degrees Pharmaceuticals, Inc.': 'SXTP', 'Pasithea Therapeutics Corp.': 'KTTA',
    'Soligenix, Inc.': 'SNGX', 'NLS Pharmaceutics AG': 'NLSP', 'Protagenic Therapeutics, Inc.': 'PTIX',
    'CERo Therapeutics Holdings, Inc.': 'CERO', 'Calidi Biotherapeutics, Inc.': 'CLDI', 'Silo Pharma, Inc.': 'SILO',
    'Acurx Pharmaceuticals, Inc.': 'ACXP', 'Entera Bio Ltd.': 'ENTX', 'Vera Therapeutics, Inc.': 'VERA',
    'Candel Therapeutics, Inc.': 'CADL', 'Palvella Therapeutics, Inc.': 'PLV', 'Tiziana Life Sciences Ltd': 'TLSA',
    'IO Biotech, Inc.': 'IOBT', 'OKYO Pharma Limited': 'OKYO', 'MoonLake Immunotherapeutics': 'MLTX',
    'aTyr Pharma, Inc.': 'ATYR', 'Viridian Therapeutics, Inc.': 'VRDN', 'SAVA Sciences, Inc.': 'SAVA',
    'AC Immune SA': 'ACIU', 'Capricor Therapeutics, Inc.': 'CAPR', 'Lexicon Pharmaceuticals, Inc.': 'LXRX',
    'Context Therapeutics Inc.': 'CNTX', 'DiaMedica Therapeutics Inc.': 'DMAC', 'Energy Fuels Inc.': 'UUUU',
    'Inhibikase Therapeutics, Inc.': 'IKT', 'Actinium Pharmaceuticals, Inc.': 'ATNM', 'TScan Therapeutics, Inc.': 'TCRX',
    'Ventyx Biosciences, Inc.': 'VTYX', 'CorMedix Inc.': 'CRMD', 'Arvinas, Inc.': 'ARVN',
    'Maze Therapeutics, Inc.': 'MAZE', 'Repare Therapeutics Inc.': 'RPTX', 'Janux Therapeutics, Inc.': 'JANX',
    'Nuvalent, Inc.': 'NUVL', 'Day One Biopharmaceuticals, Inc.': 'DAWN', 'Scholar Rock Holding Corporation': 'SRRK',
    'Karuna Therapeutics, Inc.': 'KRTX', 'Cerevel Therapeutics Holdings, Inc.': 'CERE', 'Denali Therapeutics Inc.': 'DNLI',
    'Alector, Inc.': 'ALEC', 'Enanta Pharmaceuticals, Inc.': 'ENTA', 'Travere Therapeutics, Inc.': 'TVTX',
    'Harmony Biosciences Holdings, Inc.': 'HRMY', 'Ultragenyx Pharmaceutical Inc.': 'RARE', 'BridgeBio Pharma, Inc.': 'BBIO',
    'Intellia Therapeutics, Inc.': 'NTLA', 'Editas Medicine, Inc.': 'EDIT', 'CRISPR Therapeutics AG': 'CRSP',
    'bluebird bio, Inc.': 'BLUE', 'Beam Therapeutics Inc.': 'BEAM', 'Natera, Inc.': 'NTRA',
    'Ironwood Pharmaceuticals, Inc.': 'IRWD', 'Halozyme Therapeutics, Inc.': 'HALO', 'BioMarin Pharmaceutical Inc.': 'BMRN',
    'Neurocrine Biosciences, Inc.': 'NBIX', 'United Therapeutics Corporation': 'UTHR', 'Incyte Corporation': 'INCY',
    'Exelixis, Inc.': 'EXEL', 'Sarepta Therapeutics, Inc.': 'SRPT', 'Alnylam Pharmaceuticals, Inc.': 'ALNY',
    'Biogen Inc.': 'BIIB', 'Ionis Pharmaceuticals, Inc.': 'IONS', 'Jazz Pharmaceuticals plc': 'JAZZ',
    'BioNTech SE': 'BNTX', 'Moderna, Inc.': 'MRNA', 'Vertex Pharmaceuticals Incorporated': 'VRTX',
    'Johnson & Johnson': 'JNJ', 'AbbVie Inc.': 'ABBV', 'Eli Lilly and Company': 'LLY', 'Sanofi': 'SNY',
    'Roche Holding AG': 'RHHBY', 'Novartis AG': 'NVS', 'Merck & Co., Inc.': 'MRK', 'Bristol-Myers Squibb Company': 'BMY',
    'Amgen Inc.': 'AMGN', 'Gilead Sciences, Inc.': 'GILD', 'Regeneron Pharmaceuticals, Inc.': 'REGN', 'Pfizer Inc.': 'PFE',
    'AstraZeneca PLC': 'AZN'
}